version: 2

sources:
  - name: demo
    database: spartan-buckeye-459010-i0
    schema: dbt_demo
    tables:

      - name: customers
        description: "Customer details with personal, contact, and location info"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
          - name: first_name
            description: "Customer's first name"
          - name: last_name
            description: "Customer's last name"
          - name: email
            description: "Email address"
          - name: phone_number
            description: "Phone number"
          - name: city
            description: "City of residence"
          - name: state
            description: "State of residence"
          - name: country
            description: "Country of residence"
          - name: signup_date
            description: "Date the customer signed up"
          - name: is_active
            description: "Boolean flag indicating if customer is active"

      - name: orders
        description: "Order records including quantity and product linkage"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
          - name: customer_id
            description: "Customer placing the order"
          - name: product_id
            description: "Product being ordered"
          - name: order_date
            description: "Date of the order"
          - name: quantity
            description: "Quantity ordered"
          - name: total_amount
            description: "Total amount paid for the order"

      - name: products
        description: "List of products available for sale"
        columns:
          - name: product_id
            description: "Unique identifier for each product"
          - name: product_name
            description: "Name of the product"
          - name: category
            description: "Category the product belongs to"
          - name: price
            description: "Unit price of the product"

      - name: marketing
        description: "Marketing campaign performance data"
        columns:
          - name: campaign_id
            description: "Unique identifier for each marketing campaign"
          - name: channel
            description: "Channel used for marketing"
          - name: start_date
            description: "Campaign start date"
          - name: end_date
            description: "Campaign end date"
          - name: budget
            description: "Budget allocated to campaign"
          - name: impressions
            description: "Number of times campaign was shown"
          - name: clicks
            description: "Number of clicks generated by campaign"
